toml_files = ["math_only_7b.toml"]

[data]
name = "PrimeIntellect/Skywork-OR1-RL-Data-v1-math-prime-rl-format"

[data.difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.1
max_solve_rate = 0.5


