model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "intellect-2"

collate_mode = "packing"

[train]
micro_bs = 4 # change to 8 for H200
reshard_after_forward = true

[data]
seq_length = 16000
path = "outputs"
clean_output_path = true

[optim]
warmup_steps = 1
batch_size = 512
total_steps = 10000000000000000000
step_per_rollout = 4


[optim.optim]
lr = 1e-6