[monitor.wandb]
project = "math-debug"

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"
reshard = true

[optim]
lr = 1e-6

### Orchestrator ###

[orchestrator]
batch_size = 512
micro_batch_size = 4
rollouts_per_prompt = 16
seq_len = 2048
mask_truncated_completions = false

[orchestrator.environment]
id = "simple-math"

[orchestrator.monitor.wandb.log_samples]
interval = 10
num_samples = 16

[ckpt]