model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "math-ablation"

collate_mode = "packing"
 
normalize_batch_to_token_count = false

[train]
micro_bs = 4 # 1 for h100
reshard_after_forward = true

[data]
seq_length = 2048
path = "data_rollout"

[optim]
batch_size = 512
step_per_rollout = 1
total_steps = 10000000000000000000

# [grpo]
# entropy_loss_coeff = 0

# [grpo.off_policy]
# type = "ratio"

[optim.optim]
lr = 1e-6

[ckpt]
rollout_path = "outputs"
clean_rollout_path = true